ProjectX.API/Controllers/ExperController.cs
using ProjectX.API.Helpers;
using ProjectX.API.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectX.API.Controllers
{
    public class ExperController : Controller
    {
        // GET: Exper
        public ActionResult Index()
        {
            return View();
        }


        [Authorize]
        public void normalizarImg()
        {
            List<AssetImage> arrayl = addImgae(340);
            foreach (var item in arrayl)
            {
                byte[] array = item.ImageStream;
                MemoryStream myMemStream = new MemoryStream(array);
                Image fullsizeImage = Image.FromStream(myMemStream);
                //string w = fullsizeImage.Width.ToString();
                //string h = fullsizeImage.Height.ToString();
                Image newImage = fullsizeImage.GetThumbnailImage(350, 450, null, IntPtr.Zero);
                MemoryStream myResult = new MemoryStream();
                newImage.Save(myResult, System.Drawing.Imaging.ImageFormat.Jpeg);
                //   var result = Business.AssetBC.SaveImage(myResult.ToArray());

                using (var db = DBHelper.GetDatabase())
                {
                    var assimg = db.AssetImages.Where(x => x.Id == item.Id).FirstOrDefault();
                    assimg.ImageStream = myResult.ToArray();
                    db.SaveChanges();
                }
            }

        }

        private List<AssetImage> addImgae(int id)
        {
            using (var db = DBHelper.GetDatabase())
            {
                var ids = db.AssetImages.Where(x => x.UserId == id).ToList();

                return ids;
            }
        }
    }
}

ProjectX.API/Views/Exper/Index.cshtml
@{
    ViewBag.Title = "Index";

}


<!DOCTYPE html>
<html lang="es">
<head>
    

</head>
<body>



    <input id="seed_one" type="text" name="seed_one" style="color:black" />



    <div style="margin-top:100px">
        <input type="number" id="tel" style="color:black" />
        <input type="submit" value="whats" onclick="send()" />
    </div>


    <br />
    <br />
    <div style="margin-top:100px">
        @using (Html.BeginForm("normalizarImg", "Exper", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            <input type="submit" value="normalizar" class="subir tn btn-primary" id="btns1" />
        }
    </div>

    <script>
        function previewFile() {
            var preview = document.querySelector('img'); //selects the query named img
            var file = document.querySelector('input[type=file]').files[0]; //sames as here
            var reader = new FileReader();

            reader.onloadend = function () {
                preview.src = reader.result;
            }

            if (file) {
                reader.readAsDataURL(file); //reads the data as a URL
            } else {
                preview.src = "";
            }
        }

        previewFile();  //calls the function named previewFile()
    </script>


    <script>
        function geocodeAddress(geocoder, resultsMap) {
            var geocoder = new google.maps.Geocoder();

            var address = $("#address").val();
            alert(address);
            geocoder.geocode({ 'address': address }, function (results, status) {
                if (status === 'OK') {

                    alert(results[0].geometry.location.lat() + "---" + results[0].geometry.location.lng());


                } else {
                    alert('La localización no fue satisfactoria por la siguiente razón: ' + status);
                }
            });
        }

        function send() {
            var text = "Hola!%20Te%20escribimos%20de%20sens-room.com%20Somos%20una%20pagina%20privada%20para%20generar%20encuentros%20con%20miembros%20VIP.%20Te%20invitamos%20a%20crear%20tu%20perfil%20y%20obtener%20así%20un%20medio%20adicional%20de%20publicidad%20para%20aumentar%20tus%20citas."
            alert("entro");
            var tel = $("#tel").val();
            window.location.href = 'https://api.whatsapp.com/send?phone=52' + tel + '&text=' + text
        }

    </script>

    <script src='https://cdn.rawgit.com/pguso/jquery-plugin-circliful/master/js/jquery.circliful.min.js'></script>
    <script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
    <script type="text/javascript">
        $(function () {
            var animales = ["Ardilla roja", "Gato", "Gorila occidental",
                "León", "Oso pardo", "Perro", "Tigre de Bengala"];

            $("#animal").autocomplete({ source: animales });
        });
    </script>
</body>
</html>